
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"F:\\assets\\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("487x347")
window.configure(bg = "#1E1E1E")


canvas = Canvas(
    window,
    bg = "#1E1E1E",
    height = 347,
    width = 487,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    130.125,
    200.9482421875,
    anchor="nw",
    text="Logged in as: Username",
    fill="#FFFFFF",
    font=("Inter SemiBold", 16 * -1)
)

canvas.create_rectangle(
    0.0,
    0.0,
    487.96875,
    37.275390625,
    fill="#040707",
    outline="")

canvas.create_text(
    6.77734375,
    11.1826171875,
    anchor="nw",
    text="Das CNC Products Pvt, Ltd",
    fill="#FFFFFF",
    font=("Inter Light", 13 * -1)
)

canvas.create_rectangle(
    239.91796875,
    169.43359375,
    248.05078125,
    177.56640625,
    fill="#000000",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    328.9052734375,
    96.77734375,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=86.4111328125,
    y=264.994140625,
    width=92.171875,
    height=42.3583984375
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=317.5185546875,
    y=264.994140625,
    width=92.171875,
    height=42.3583984375
)
window.resizable(False, False)
window.mainloop()
